// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */

import type { LocalizedString } from 'typesafe-i18n'

export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'hu'

export type Translation = {
	/**
	 * Theme selector
	 */
	'themeSelector': string
}

export type TranslationFunctions = {
	/**
	 * Theme selector
	 */
	'themeSelector': () => LocalizedString
}

export type Formatters = {}
