// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */

import type { LocalizedString } from 'typesafe-i18n'

export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'hu'

export type Translation = {
	/**
	 * Settings
	 */
	'modalTitleSettings': string
	/**
	 * Theme selector
	 */
	'themeSelector': string
	/**
	 * Language selector
	 */
	'languageSelector': string
	/**
	 * Start typing here
	 */
	'wordInputPlaceholder': string
}

export type TranslationFunctions = {
	/**
	 * Settings
	 */
	'modalTitleSettings': () => LocalizedString
	/**
	 * Theme selector
	 */
	'themeSelector': () => LocalizedString
	/**
	 * Language selector
	 */
	'languageSelector': () => LocalizedString
	/**
	 * Start typing here
	 */
	'wordInputPlaceholder': () => LocalizedString
}

export type Formatters = {}
